# Generated by Django 2.1.5 on 2019-01-12 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='username',
            new_name='category_name',
        ),
    ]
